---
title: "Seminarska"
author: "Ne탑a Kr탑an, Tom Rupnik Medjedovi훾"
date: "2024-02-27"
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install.packages("rjson")
library("rjson")
library(shiny)
library(plotly)
library(dplyr)
library(tidyverse)
library(highcharter)
library(tidyr)
```

```{r include=FALSE}
#podatki = read.csv("podatki.csv", sep=';')

podatki = read.csv("podatki.csv", sep=';', na.strings = "...")

# ime stolpca Vzork.smrti --> stevilo
colnames(podatki)[5] = "stevilo"

# ime stolpca Vzrok.smrti.na.1000.prebivalcev --> stevilo1000
colnames(podatki)[6] = "stevilo1000"

# Vzrok smrti - SKUPAJ --> skupaj
# podatki[podatki$VZROK.SMRTI=="Vzrok smrti - SKUPAJ", "VZROK.SMRTI"] = "skupaj"

# Nekatere infekcijske in parazitske bolezni (A00-B99) --> vzrok1
# podatki[podatki$VZROK.SMRTI=="Nekatere infekcijske in parazitske bolezni (A00-B99)", "VZROK.SMRTI"] = "vzrok1"

# Neoplazme (C00-D48) --> vzrok2
# podatki[podatki$VZROK.SMRTI=="Neoplazme (C00-D48)", "VZROK.SMRTI"] = "vzrok2"

# Bolezni obtocil (I00-I99) --> vzrok3
# podatki[podatki$VZROK.SMRTI=="Bolezni obtocil (I00-I99)", "VZROK.SMRTI"] = "vzrok3"

# Bolezni dihal (J00-J99) --> vzrok4
# podatki[podatki$VZROK.SMRTI=="Bolezni dihal (J00-J99)", "VZROK.SMRTI"] = "vzrok4"

# Bolezni prebavil (K00-K93) --> vzrok5
# podatki[podatki$VZROK.SMRTI=="Bolezni prebavil (K00-K93)", "VZROK.SMRTI"] = "vzrok5"

# Poskodbe, zastrupitve in nekatere druge posledice zunanjih vzrokov (S00-T98) --> vzrok6
# podatki[podatki$VZROK.SMRTI=="Poskodbe, zastrupitve in nekatere druge posledice zunanjih vzrokov (S00-T98)", "VZROK.SMRTI"] = "vzrok6"
```

```{r include=FALSE}
# zapomnimo si indeks vrstic, ki nimajo stevila umrlih
# katere_prazne = NULL
# for(i in 1:nrow(podatki)){
  # if(podatki[i,]$stevilo == "..."){
    # katere_prazne = c(katere_prazne,i)
  # }
# }

# vrstice, ki nimajo podatka(stevila)
# vrstice_brez = podatki[katere_prazne,]

# vrstice, ki imajo podatek(stevilo)
# vrstice_dobre = podatki[-katere_prazne,]
# leto spremenimo iz chr v int
# vrstice_dobre$stevilo = as.integer(vrstice_dobre$stevilo)
# vrstice_dobre$stevilo1000 = as.double(vrstice_dobre$stevilo1000)

df_mankajoce_vrednosti = podatki[!complete.cases(podatki), ]
df = na.omit(podatki)
```


```{r include=FALSE}
# primer iskanja
podatki[c(podatki$VZROK.SMRTI=="skupaj" & podatki$LETO=="2002"),]
```

```{r include=FALSE}
iskanje_vrstic = function(vzrok, regija, spol, leto){
  # iscemo le po "dobrih" vrsticah
  podatki_dobri = vrstice_dobre
  
  rezultat = podatki_dobri[c(podatki_dobri$VZROK.SMRTI %in% vzrok &
                       podatki_dobri$KOHEZIJSKA.REGIJA %in% regija &
                       podatki_dobri$SPOL %in% spol &
                       podatki_dobri$LETO %in% leto),]
  
  rezultat = data.frame(rezultat)
  return(rezultat)
}

#podatki = read.csv("podatki.csv", sep=';', na.strings = "...")

# primer iskanja podatkov
#aa = iskanje_vrstic(c("skupaj", "vzrok1"), "SLOVENIJA", "Spol - SKUPAJ", c(2002:2022))
```

### Stevilo smrti glede na vzrok
#### od 2002 do 2022

```{r echo=FALSE, fig.align='center', fig.height=5, fig.width=10}
df1 = podatki[podatki$KOHEZIJSKA.REGIJA == "SLOVENIJA" & podatki$SPOL == "Spol - SKUPAJ", 1:5]
df1.1 = spread(df1, VZROK.SMRTI, stevilo)

h <- highchart() %>% 
  hc_xAxis(categories = df1.1$LETO) %>% 
  hc_add_series(name = "Bolezni dihal (J00-J99)", 
                data = df1.1$`Bolezni dihal (J00-J99)`) %>% 
  hc_add_series(name = "Bolezni obtocil (I00-I99)", 
                data = df1.1$`Bolezni obtocil (I00-I99)`) %>%
  hc_add_series(name = "Bolezni prebavil (K00-K93)", 
                data = df1.1$`Bolezni prebavil (K00-K93)`) %>%
  hc_add_series(name = "Nekatere infekcijske in parazitske bolezni (A00-B99)", 
                data = df1.1$`Nekatere infekcijske in parazitske bolezni (A00-B99)`) %>%
  hc_add_series(name = "Neoplazme (C00-D48)", 
                data = df1.1$`Neoplazme (C00-D48)`) %>%
  hc_add_series(name = "Poskodbe, zastrupitve in nekatere druge posledice zunanjih vzrokov (S00-T98)", 
                data = df1.1$`Poskodbe, zastrupitve in nekatere druge posledice zunanjih vzrokov (S00-T98)`)

# customize interactive line chart
h <- h %>%
  hc_tooltip(crosshairs = TRUE, 
             backgroundColor = "white",
             borderWidth = 2) %>% 
  hc_exporting(enabled = TRUE)

h
```

### Stevilo umrlih zensk in moskih po vzroku
#### od leta 2002 do 2022

```{r echo=FALSE, fig.height=10, fig.width=14, message=FALSE, warning=FALSE}
# devtools::install_github("teunbrand/ggh4x")
library(tidyverse)
library(geofacet)
library(ggh4x)
library(streamgraph)
library(hrbrthemes)
library(ggtext)

df1 <- podatki[podatki$KOHEZIJSKA.REGIJA =="SLOVENIJA" & podatki$SPOL =="Moski" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ",]
df2 <- podatki[podatki$KOHEZIJSKA.REGIJA =="SLOVENIJA" & podatki$SPOL =="Zenske" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ",]

df = na.omit(data.frame(moski.s = df1$stevilo, zenske.s = df2$stevilo, leto = df1$LETO, vzrok = df1$VZROK.SMRTI))

df[df$vzrok =="Poskodbe, zastrupitve in nekatere druge posledice zunanjih vzrokov (S00-T98)", "vzrok"] = "Poskodbe, zastrupitve, zunanji vzroki (S00-T98)"

ggplot(df, aes(x = leto)) +
  geom_line(aes(y = zenske.s, color = "zenske"), size=1.1) +
  geom_line(aes(y = moski.s, color = "moski"), size=1.1) +
  scale_color_manual(values = c('zenske' = 'pink', 'moski' = 'lightblue')) +
  scale_x_continuous(breaks=seq(2002, 2022, 3)) +
  scale_y_continuous(breaks=seq(500, 5000, 600)) +
  labs(color = 'SPOL') +
  theme_ipsum(grid="Y", strip_text_size = 14, axis_text_size = 12, axis_title_size = 12) +
  xlab("leto") + ylab("stevilo umrlih") +
  facet_wrap(~vzrok) +
  theme(plot.title = element_text(color = "black", size = 20, face = "bold"),
        plot.subtitle = element_markdown(color = "grey", size = 16),
        legend.position="bottom",
        legend.text=element_text(size=16),
        legend.title=element_text(size=16))
```

### Dele탑 smrti glede na vzrok po kohezijskih regijah

```{r eval=FALSE, fig.align="center", include=FALSE}
selectInput("izbrano_leto", label="Izberite leto", choices = unique(podatki$LETO), selected = 2002)

selectInput("izbran_spol", label="Izberite spol", choices = c("Moski", "Zenske"), selected = "Moski")

df2 = podatki[podatki$KOHEZIJSKA.REGIJA %in% c("Vzhodna Slovenija", "Zahodna Slovenija") & podatki$SPOL %in% c("Moski", "Zenske") &
              podatki$VZROK.SMRTI %in% unique(podatki$VZROK.SMRTI)[2:7],]

renderPlot({
  df2.1 = na.omit(df2[df2$SPOL == input$izbran_spol &
              df2$LETO == as.numeric(input$izbrano_leto),])
  df2.1 = df2.1[order(-df2.1$stevilo),]
  
  ggplot(df2.1, aes(x="", y=stevilo, fill= reorder(VZROK.SMRTI, order(-stevilo)))) +
    geom_bar(stat="identity", width=1, color="white", position = "fill", border="white") +
    facet_grid(~KOHEZIJSKA.REGIJA) +
    coord_polar(theta="y") + 
    theme_void() +  labs(fill='Vzrok smrti') +
    theme(axis.text.x = element_text(angle=-20)) 

})
```


```{r message=FALSE, warning=FALSE, include=FALSE}
mz = podatki[podatki$SPOL == "Moski" & podatki$KOHEZIJSKA.REGIJA == "Zahodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]
mv = podatki[podatki$SPOL == "Moski" & podatki$KOHEZIJSKA.REGIJA == "Vzhodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]
zz = podatki[podatki$SPOL == "Zenske" & podatki$KOHEZIJSKA.REGIJA == "Zahodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]
zv = podatki[podatki$SPOL == "Zenske" & podatki$KOHEZIJSKA.REGIJA == "Vzhodna Slovenija" & podatki$VZROK.SMRTI != "Vzrok smrti - SKUPAJ", ]

df = na.omit(data.frame(leto = mz$LETO,
                stevilo.v = c(mv$stevilo,zv$stevilo),
                stevilo.z = c(mz$stevilo, zz$stevilo),
                vzrok = c(mz$VZROK.SMRTI,zz$VZROK.SMRTI),
                spol = c(mz$SPOL, zz$SPOL)))
```

```{r echo=FALSE, fig.height=7, fig.width=11, message=FALSE, warning=FALSE, fig.align="center"}
ui <- fluidPage(
  headerPanel(''),
  sidebarPanel(
    selectInput("izbrano_leto", label="Izberite leto", choices = sort(unique(df$leto)), selected = 2002),
    selectInput("izbran_spol", label="Izberite spol", choices = c("Moski", "Zenske"), selected = "Moski")
    #selected = names(mtcars)[[2]]
    ),
  mainPanel(
    plotlyOutput('plot')
  )
)

server <- function(input, output) {
  
  data <- reactive({

    req(input$izbrano_leto,input$izbran_spol)
    
    df %>% 
      select(leto, stevilo.v, stevilo.z, spol, vzrok) %>%
      filter(leto %in% input$izbrano_leto, spol %in% input$izbran_spol)
  })
  
  output$plot <- renderPlotly(
    plot_ly(marker = list(line = list(color = 'white', width = 1)),) %>%
      add_pie(data = data(), labels = ~vzrok, values = ~stevilo.z,
              name = "Zahodna Slovenija", 
              domain = list(x = c(0, 0.4), y = c(0.1, 0.92))) %>% 
      add_pie(data = data(), labels = ~vzrok, values = ~stevilo.v,
              name = "Vzhodna Slovenija",
              domain = list(x = c(0.58, 0.98), y = c(0.1, 0.92))) %>% 
      layout(title = "", showlegend = T,
             xaxis = list(showgrid = F, zeroline = FALSE, showticklabels = FALSE),
             yaxis = list(showgrid = F, zeroline = FALSE, showticklabels = FALSE),
             legend = list(x = 0, y = 0.05, orientation = 'h')) %>%
      add_annotations(x=c(0.082, 0.68), y=1, text = c("Zahodna Slovenija", "Vzhodna Slovenija"), 
                      xref = "paper", yref = "paper", xanchor = "left", showarrow = FALSE)
  )
}

shinyApp(ui,server)
```


```{r}
# library(rsconnect)
# rsconnect::deployDoc('Test2.Rmd')
```

