install.packages(c(
  "shiny",
  "plotly",
  "dplyr",
  "tidyverse",
  "highcharter",
  "tidyr",
  "tidyverse",
  "geofacet",
  "ggh4x",
  "streamgraph",
  "hrbrthemes",
  "ggtext"
))
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
